# Opérations NumPy

## Arithmétique

Vous pouvez facilement effectuer des opérations arithmétiques *array avec array*, ou *scalaire avec array*. Voyons quelques exemples :

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Cela entraînera un avertissement sur la division par zéro, mais pas une erreur !
# Il remplit juste l'emplacement' avec du nan
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Egalement un avertissement (mais pas une erreur) relatif à l'infini
1 / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Fonctions de tableau universelles

NumPy est fourni avec de nombreuses [fonctions de tableau universelles] (http://docs.scipy.org/doc/numpy/reference/ufuncs.html), ou <em>ufuncs</em>, qui sont simplement des opérations mathématiques pouvant être appliquées à l'ensemble du tableau :

In [ ]:
# Racine carrée
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# Calculer l'exponentielle (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
# Fonctions trigonométriques comme le sinus
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
# Prendre le logarithme
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Statistiques sommaires sur les tableaux

NumPy propose également des statistiques récapitulatives communes telles que <em>somme</em>, <em>moyenne</em> et <em>max</em>. On les appelle comme des méthodes sur un tableau.

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

<strong> D'autres statistiques sommaires incluent :</strong>
<pre>
arr.min() retourne 0, c'est le minimum
arr.var() retourne une variance de 8,25
arr.std() retourne 2,8722813232690143, c'est l'écart type
</pre>

## Logique des axes
Lorsque nous travaillons avec des tableaux à deux dimensions (matrices), nous devons tenir compte des lignes et des colonnes. Cela devient très important lorsque nous arrivons à la section sur Pandas. En termes de tableaux, l'axe 0 (zéro) est l'axe vertical (lignes), et l'axe 1 est l'axe horizontal (colonnes). Ces valeurs (0,1) correspondent à l'ordre dans lequel les valeurs <tt>arr.shape</tt> sont retournées.

Voyons comment cela affecte nos calculs de statistiques sommaires vus ci-dessus.

In [ ]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

En passant <tt>axis=0</tt>, nous retournons un tableau de sommes le long de l'axe vertical, c'est-à-dire <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='https://drive.google.com/uc?export=view&id=1MuhzdKMF-knlcNX4rm3hBD8x1j3Abb0L' width=400/>

In [ ]:
arr_2d.shape

(3, 4)

Cela nous indique que <tt>arr_2d</tt> a 3 lignes et 4 colonnes.

Dans <tt>arr_2d.sum(axis=0)</tt> ci-dessus, le premier élément de chaque ligne a été additionné, puis le deuxième élément, et ainsi de suite.

Que doit donc retourner <tt>arr_2d.sum(axis=1)</tt> ?

In [ ]:
# REFLECHISSEZ À CE QUE CELA DOIT VOUS RETOURNER AVANT D'EXECUTER LA CELLULE' !
arr_2d.sum(axis=1)

# Bon Travail !

C'est tout ce que nous avons besoin de savoir pour l'instant !